package Payload;

public class OrderPayload {
	public static String payloadOrder(String orderID) {
		String orderPayload = " {\r\n"
				+ "          \"user\": {\r\n"
				+ "            \"id\": 12345,\r\n"
				+ "            \"name\": \"John Doe\",\r\n"
				+ "            \"email\": \"john.doe@example.com\",\r\n"
				+ "            \"preferences\": {\r\n"
				+ "              \"notifications\": {\r\n"
				+ "                \"email\": true,\r\n"
				+ "                \"sms\": false,\r\n"
				+ "                \"push\": {\r\n"
				+ "                  \"enabled\": true,\r\n"
				+ "                  \"frequency\": \"daily\"\r\n"
				+ "                }\r\n"
				+ "              },\r\n"
				+ "              \"privacy\": {\r\n"
				+ "                \"profileVisibility\": \"friends_only\",\r\n"
				+ "                \"lastSeen\": false\r\n"
				+ "              }\r\n"
				+ "            },\r\n"
				+ "            \"addresses\": [\r\n"
				+ "              {\r\n"
				+ "                \"type\": \"home\",\r\n"
				+ "                \"street\": \"123 Main St\",\r\n"
				+ "                \"city\": \"New York\",\r\n"
				+ "                \"state\": \"NY\",\r\n"
				+ "                \"postalCode\": \"10001\",\r\n"
				+ "                \"geo\": {\r\n"
				+ "                  \"lat\": 40.7128,\r\n"
				+ "                  \"lng\": -74.0060\r\n"
				+ "                }\r\n"
				+ "              },\r\n"
				+ "              {\r\n"
				+ "                \"type\": \"work\",\r\n"
				+ "                \"street\": \"456 Park Ave\",\r\n"
				+ "                \"city\": \"New York\",\r\n"
				+ "                \"state\": \"NY\",\r\n"
				+ "                \"postalCode\": \"10022\",\r\n"
				+ "                \"geo\": {\r\n"
				+ "                  \"lat\": 40.7590,\r\n"
				+ "                  \"lng\": -73.9845\r\n"
				+ "                }\r\n"
				+ "              }\r\n"
				+ "            ],\r\n"
				+ "            \"roles\": [\"user\", \"admin\"],\r\n"
				+ "            \"metadata\": {\r\n"
				+ "              \"createdDate\": \"2021-10-10T10:00:00Z\",\r\n"
				+ "              \"updatedDate\": \"2023-01-15T12:00:00Z\"\r\n"
				+ "            }\r\n"
				+ "          },\r\n"
				+ "          \"session\": {\r\n"
				+ "            \"token\": \"abcdef123456\",\r\n"
				+ "            \"expires\": \"2025-12-31T23:59:59Z\",\r\n"
				+ "            \"ip\": \"192.168.1.10\",\r\n"
				+ "            \"device\": {\r\n"
				+ "              \"type\": \"mobile\",\r\n"
				+ "              \"os\": \"Android\",\r\n"
				+ "              \"appVersion\": \"5.2.1\",\r\n"
				+ "              \"location\": {\r\n"
				+ "                \"country\": \"USA\",\r\n"
				+ "                \"region\": \"Northeast\",\r\n"
				+ "                \"city\": \"New York\"\r\n"
				+ "              }\r\n"
				+ "            }\r\n"
				+ "          }\r\n"
				+ "        }\r\n";
				return orderPayload;
	}
	
}
